steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/<project-id>/video_summary', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/<project-id>/video_summary']

logsBucket: 'gs://article_creation_bucket'
options:
  logging: GCS_ONLY

images:
- gcr.io/<project-id>/video_summary